equinor/terraform-azurerm-storage

- README.md
- main.tf
Remove role assignment for current client, as role "Storage Blob Data Contributor" is not required to create Containers when shared access key is disabled.
> refactor: remove client role assignment

- .github/workflows/release.yml
Fixes error in semantic release workflow: https://github.com/equinor/terraform-azurerm-storage/runs/6485604423?check_suite_focus=true
> chore: Add required semantic release extra module

- .github/workflows/release.yml
- .releaserc.json
Remove semantic-release plugins that require PAT token.
Remove lines that were only relevant due to these plugins.
Ref: https://github.com/cycjimmy/semantic-release-action#basic-usage
> ci: Remove semantic-release plugins that require PAT token

- README.md
- main.tf
- test/fixture/main.tf
- variables.tf
BREAKING CHANGE: Rename variable 'network_ip_rules' to 'firewall_ip_rules'.
To migrate your project, change all module calls where you use variable 'network_ip_rules' with 'firewall_ip_rules'.
> refactor!: Rename variable

- README.md
- test/fixture/main.tf
Not required because shared access key is enabled by default.
> docs(readme): remove redundant provider feature in usage example

- .github/workflows/release.yml
- .releaserc.json
Remove trigger on branch master to prevent contributors from creating a branch master and triggering a release.
> ci(release): Remove trigger on branch master

- main.tf
[Storage account name can only contain lowercase letters and numbers](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage). This module will fail if no custom storage account name is provided and variable "environment" contains a hyphen.
To prevent this error, concat variables "application" and "environment" in a local variable "suffix", convert this local variable to lowercase letter and numbers, then store the value in another local variable "suffix_alnum". Use this local variable to set the name for the storage account.
> fix: prevent error when environment contains hyphen

- main.tf
Add default values to arguments to prevent Terraform from reporting these as "changed outside of Terraform".
> refactor: add default values for arguments

- README.md
- main.tf
- test/fixture/main.tf
- variables.tf
- versions.tf
**BREAKING CHANGE**: Enable point-in-time-restore. To migrate your project, remove any references to input variables `account_tier`, `blob_versioning_enabled`, `blob_change_feed_enabled` and `blob_delete_retention_policy` in all calls to this module. If `account_tier` was set to `Premium`, migration will require recreation of the storage account.
Point-in-time restore requires soft-delete to be enabled. A lifecycle management policy has been added to delete old versions.
Point-in-time restore does not prevent accidental deletion of the storage account itself. A delete-lock has been added to prevent this.
Closes #44
Closes #45
Closes #46
- https://docs.microsoft.com/en-us/azure/storage/blobs/point-in-time-restore-overview
> feat!: enable point-in-time restore

- README.md
- main.tf
- test/fixture/main.tf
- variables.tf
Data protection features should be optional. Create new variables for enabling/disabling blob versioning, change feed and point-in-time restore.
> feat: optional data protection features

- README.md
- main.tf
- versions.tf
AzAPI provider currently does not support OIDC authentication. (Azure/terraform-provider-azapi#101)
Comment out until this is supported.
> feat: remove blob pitr

- outputs.tf
Module currently throws an error if an identity is not configured.
> fix: don't output non-existent attributes

- examples/cmk/main.tf
- main.tf
Rename diagnostic settings to `audit-logs` to better represent what logs are being send to log analytics.
> refactor: rename diagnostic settings

- main.tf
- variables.tf
We use diagnostic settings instead.
Fixes #127
> feat!: remove queue properties logging and metrics

- examples/cmk/outputs.tf
Add the standard outputs which are in the other examples.
> chore: add outputs to cmk example

- main.tf
Fixes Bug: "access_tier"  default value causes issues with accounts of kind "BlockBlobStorage" #198
> fix: only configure access tier for supported account kinds

- examples/premium-block-blob-storage/main.tf
- examples/premium-data-lake-storage/main.tf
- examples/premium-file-storage/main.tf
- examples/premium-gpv2-storage/main.tf
- examples/standard-blob-storage/main.tf
- examples/standard-data-lake-storage/main.tf
- examples/standard-gpv2-storage/main.tf
Examples should use remote sources, as per [standard module structure](https://developer.hashicorp.com/terraform/language/modules/develop/structure).
Forcing a patch release to push this to the registry.
Release-As: 12.4.1
> chore: use remote module sources in examples

- main.tf
- variables.tf
Added a private_link_access block as optional and will only be created if list of endpoint_resource_ids is specified.
> feat: add private link access

- variables.tf
Default to Entra ID authorization in Azure Portal. There'll still be an option to switch to shared key authorization if needed.
If shared key access is enabled, we should still promote use of Entra ID authorization where possible. For example, even though an application requires shared key authorization, users might still be able to use Entra ID.
> feat: default to Entra ID authorization in Azure Portal

- README.md
- examples/premium-block-blob-storage/main.tf
- examples/premium-data-lake-storage/main.tf
- examples/premium-file-storage/main.tf
- examples/premium-gpv2-storage/main.tf
- examples/standard-blob-storage/main.tf
- examples/standard-data-lake-storage/main.tf
- examples/standard-gpv2-storage/main.tf
- Update README to clarify that subscription ID must be set as an environment variable.
- Update examples to use local path in module source, ensuring the examples always use the latest version of the module that supports the latest version of the Azure provider.
> fix: examples don't work with Azure provider v4

- variables.tf
Move to the new Defender for Storage plan instead: https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-classic-migrate
> feat: disable Defender for Storage (classic) by default

- README.md
Terraform Registry doesn't support relative links.
> fix: broken link to license

- main.tf
- tests/monitoring.tftest.hcl
- versions.tf
- Replace argument `metric` with `enabled_metric`.
- Bump minimum allowed Azure provider version. Version 4.31.0 is required to use the `enabled_metric` argument.
> fix: argument `metric` for resource `azurerm_monitor_diagnostic_setting` has been deprecated

- main.tf
- moved.tf
- tests/monitoring.tftest.hcl
Currently Terraform Registry lists 1 diagnostic setting to be created by this module. This is misleading, since in reality 4 diagnostic resources are created by a `for_each` loop.
Update this module to explicitly create 4 diagnostic setting resources, which results in Terraform Registry listing 4 diagnostic setting resources to be created.
Release-As: 12.13.2
> refactor: create explicit diagnostic setting resources
