equinor/terraform-azurerm-storage

README.md, versions.tf
Upgrade azurerm provider version to the latest supporting version.
=> modify: upgrade azurerm provider version

README.md, outputs.tf
Add output `account_id`.
Add output `account_name`.
Add output `blob_endpoint`.
Add output `queue_endpoint`.
Add output `table_endpoint`.
Add output `file_endpoint`.
Add output `primary_access_key`.
Add output `secondary_access_key`.
Add output `primary_connection_string`.
Add output `secondary_connection_string`.
=> feat: add outputs

README.md, main.tf, test/fixture/main.tf, variables.tf
Add variable 'log_analyics_workspace_id'.
Add resource 'azurerm_monitor_diagnostic_setting.this'.
Update usage example.
Update test fixture.
=> feat: add diagnostic settings

README.md, main.tf, variables.tf
Add a share_properties block with a rentention policy under the azurerm storage account resource.
=> feat: add file rentention policy

README.md, main.tf, test/fixture/main.tf, test/fixture/versions.tf, variables.tf, versions.tf
Disable anonymous public access by default to improve security. Allow public access to be enabled if required.
=> feat: disable blob public access by default

README.md, main.tf, variables.tf
Set custom retention and restore policies to either reduce costs or improve resilience.
Closes #49
=> feat: set custom retention and restore policies

README.md
=> docs(readme): missing quote in usage example

README.md, main.tf, variables.tf
Enable threat protection (Microsoft Defender) by default to detect unusual and potentially harmful attempts to access or exploit this Storage Account.
Closes #48
=> feat: enable threat protection

README.md, main.tf, test/fixture/main.tf, variables.tf
=> feat!: remove data plane resources

README.md, main.tf
Remove resource lock to lower the required role to use this module from "Owner" to "Contributor".
Closes #61
=> feat!: remove resource lock

README.md, test/fixture/main.tf, test/fixture/versions.tf, versions.tf
Remove providers that are no longer needed to reduce number of dependencies.
=> chore: remove unused providers

main.tf
=> fix: don't set blob or share properties if blob or file storage is disabled

main.tf, variables.tf
Rename variables according to baseline.
=> refactor!: rename variables

main.tf, variables.tf
=> feat: set identity type and ids

main.tf, versions.tf
https://github.com/equinor/terraform-azurerm-storage/issues/126
=> refactor: update min. provider version

examples/premium-block-blob-storage/main.tf, examples/premium-data-lake-storage/main.tf, examples/premium-file-storage/main.tf, examples/premium-gpv2-storage/main.tf, examples/standard-blob-storage/main.tf, examples/standard-data-lake-storage/main.tf, examples/standard-gpv2-storage/main.tf, main.tf, variables.tf
https://github.com/equinor/terraform-azurerm-storage/issues/131
=> feat: set log analytics destination type

examples/premium-gpv2-storage/main.tf, main.tf
Added feature to remove blob restore policy when account tier is set to "standard"
=> refactor: add check for blob properties restore policy

examples/premium-block-blob-storage/main.tf, examples/premium-file-storage/main.tf, examples/premium-gpv2-storage/main.tf, examples/standard-blob-storage/main.tf, main.tf
Improve checks for which features are supported for different tiers and kinds.
=> refactor: improve checks for supported features

main.tf, variables.tf
=> feat: disable cross-tenant replication by default

main.tf, variables.tf
Enforce network ACLs default action value of "Deny" to increase security
BREAKING CHANGE: remove variable network_acls_default_action
=> feat!: enforce network ACLs default action

examples/cmk/main.tf, main.tf, variables.tf
BREAKING CHANGE: remove variable `identity`, add variables `system_assigned_identity_enabled` and `identity_ids`.
=> refactor!: simplify identity configuration

main.tf, variables.tf
=> feat!: enforce advanced treat protection

main.tf, variables.tf
=> feat!: enforce share properties

examples/cmk/main.tf, main.tf, variables.tf
=> feat!: enforce blob properties

main.tf, variables.tf
Validate network IP rules to prevent passing invalid values to Storage account resource.
=> fix: validate network IP rules

README.md
Update usage section in README as defined in equinor/terraform-baseline#80.
=> docs: update usage section in README

main.tf
Restore blocks that were accidentally removed by the script-created PR #187.
=> fix: restore accidentally removed blocks

main.tf, variables.tf
=> feat: disable advanced threat protection

main.tf, variables.tf
added the `default_to_oauth_authentication` attribute, with default set to `false`
=> feat: default to OAuth authentication

main.tf
Reverse conditional value `azurerm_storage_account.this.network_rules[0].bypass` to enable trusted Microsoft services access by default (SNYK-CC-TF-172).
=> refactor: reverse conditional value

main.tf, variables.tf
Add a diagnostic setting name to module, to set custom name.
=> feat: add diagnostic setting name variable

main.tf, outputs.tf, variables.tf
- Update variable descriptions.
- Update output descriptions.
- Add/update variable validations.
- Add preconditions.
=> refactor: update variable and output descriptions and validations

main.tf, variables.tf
Add possibility to set cors rule for file share service
=> feat: add cors rules for file share service

main.tf, versions.tf
[Ref.](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#azurerm_storage_account)
=> refactor: replace deprecated arguments

main.tf, tests/unit.tftest.hcl
Fixes equinor/terraform-baseline#181
Release-As: 12.7.3
=> refactor: don't configure network rules if default action is "Allow"

main.tf, tests/unit.tftest.hcl
`azurerm_storage_account.this.network_rules[0].bypass` set to `[]` when it should be set to `["None"]`.
=> fix: incorrect config when variable `network_rules_bypass_azure_services` set to `false`

README.md
- Update header to reflect repo name (`terraform-azurerm-storage` reads as "**Terraform** module for **Azure** **Storage**").
- Update badges to highlight repo status (license, latest release, commit spec and Equinor SCM compliance).
- Update description to reflect that this module creates Azure Storage **resources**, not just a Storage **account**.
=> docs: update header, badges and description in README

main.tf, tests/unit.tftest.hcl, variables.tf
Add variable `infrastructure_encryption_enabled` to allow enabling infrastructure encryption.
Ref: https://learn.microsoft.com/en-us/azure/storage/common/infrastructure-encryption-enable
=> feat: configure infrastructure encryption

README.md
=> docs: clarify kind of Storage account created by default

main.tf
Remove locals that are only referenced once. A local should be referenced at least twice to have a purpose.
=> refactor: remove redundant locals

variables.tf
=> docs: clarify why advanced threat protection is disabled by default

outputs.tf
Add outputs `dfs_endpoint` and `secondary_dfs_endpoint`.
=> feat: output Data Lake Storage endpoints
